[client]
toolbarMode = "viewer"  # Hides deploy button and dev tools

[server]
enableStaticServing = false

[theme]
primaryColor = "#2c3e50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
